// t13_4_xdp_loader.cpp — T13.4 FINAL: in-kernel SYN scan detection
// loaded as a SECONDARY BPF program alongside skel_soc.
//
// Architecture (per user decision 2026-06-17):
//   - This is a SECONDARY observability program. It does NOT replace
//     skel_soc — both run in parallel.
//   - skel_soc still does FIM/execve/unlinkat (existing V3.x/V4.x behavior).
//   - t13_4_xdp does in-kernel SYN scan detection via XDP.
//   - Alerts are pushed into the same EventBus (T12) as a synthetic
//     type 9 event (SCAN_DETECTED). The ActionRecommender (T13.3')
//     can then optionally recommend a firewall rule.
//
// Why in-kernel:
//   - Zero packet copy to userspace (vs pcap_collector which copies
//     every packet via libpcap, then IPC's a summary up — 2 hops).
//   - The kernel only emits a small ring buffer event when a
//     SCAN is detected. No copy on the happy path.
//
// Why alongside pcap_collector (T13.4' follow-up will replace):
//   - The existing pcap collector has years of tuning and is
//     deeply integrated with the rest of the agent. Replacing
//     it would be a separate, large refactor (T13.4').
//   - For now, XDP is a side-car that runs ONLY if the operator
//     has set enable_xdp_scan=true in /etc/logsoc-agent/config.json.
//
// The XDP program is embedded as t13_4_xdp_bpf[] in
// t13_4_xdp_payload.h (generated by scripts/build_ebpf.sh).
//
// API:
//   bool t13_4_xdp_init(const std::string& ifname, void (*event_cb)(...));
//   void t13_4_xdp_stop();

#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <linux/if_link.h>
#include <net/if.h>
#include <sys/resource.h>
#include <unistd.h>
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <mutex>
#include <string>

// T13.4 XDP payload (auto-generated by scripts/build_ebpf.sh)
extern "C" {
#include "../t13_4_xdp_payload.h"
}

namespace ebpf {

// --- T13.4 XDP state (singleton, protected by g_t13_4_mtx) ---
static struct {
    struct bpf_object* obj = nullptr;
    struct bpf_program* prog = nullptr;
    struct bpf_map* counters_map = nullptr;
    struct bpf_map* syn_map = nullptr;
    struct bpf_map* alerts_map = nullptr;
    struct ring_buffer* rb = nullptr;
    int ifindex = 0;
    std::atomic<bool> running{false};
    // Event callback (set at init() time)
    void (*scan_event_cb)(uint32_t src_ip, uint32_t dst_ip,
                          uint16_t dst_port, uint64_t syn_count) = nullptr;
} g_t13_4;

static std::mutex g_t13_4_mtx;

// Kernel event struct (mirror of alert_event in t13_4_xdp.bpf.c)
struct XdpAlertEvent {
    uint32_t src_ip;
    uint32_t dst_ip;
    uint16_t dst_port;
    uint16_t pad;
    uint64_t syn_count;
    uint64_t timestamp_ns;
};

// Ring buffer event handler — invoked by libbpf on each event
static int t13_4_handle_event(void* /*ctx*/, void* data, size_t len) {
    if (len < sizeof(XdpAlertEvent)) return -1;
    auto* e = reinterpret_cast<XdpAlertEvent*>(data);
    if (g_t13_4.scan_event_cb) {
        g_t13_4.scan_event_cb(e->src_ip, e->dst_ip, e->dst_port, e->syn_count);
    }
    return 0;
}

// Initialize the XDP program. Must be called AFTER setrlimit(RLIMIT_MEMLOCK, INF)
// which the agent's main() does anyway.
//
// Returns true on success, false on any failure (logged).
bool t13_4_xdp_init(const std::string& ifname,
                    void (*scan_event_cb)(uint32_t, uint32_t, uint16_t, uint64_t)) {
    std::lock_guard<std::mutex> lk(g_t13_4_mtx);

    if (g_t13_4.running) {
        std::fprintf(stderr, "[T13.4] already running on ifindex %d\n", g_t13_4.ifindex);
        return true;
    }

    int ifindex = if_nametoindex(ifname.c_str());
    if (ifindex == 0) {
        std::fprintf(stderr, "[T13.4] if_nametoindex(%s) failed: %s\n",
                     ifname.c_str(), std::strerror(errno));
        return false;
    }

    // Open + load the BPF object (embedded)
    g_t13_4.obj = bpf_object__open_mem(
        reinterpret_cast<const char*>(t13_4_xdp_bpf),
        sizeof(t13_4_xdp_bpf),
        nullptr);
    if (!g_t13_4.obj) {
        std::fprintf(stderr, "[T13.4] bpf_object__open_mem failed\n");
        return false;
    }
    if (bpf_object__load(g_t13_4.obj) != 0) {
        std::fprintf(stderr, "[T13.4] bpf_object__load failed: %s\n",
                     std::strerror(errno));
        bpf_object__close(g_t13_4.obj);
        g_t13_4.obj = nullptr;
        return false;
    }

    // Find the program + maps
    g_t13_4.prog = bpf_object__find_program_by_name(g_t13_4.obj, "xdp_scan_detect");
    if (!g_t13_4.prog) {
        std::fprintf(stderr, "[T13.4] no xdp_scan_detect program found\n");
        bpf_object__close(g_t13_4.obj);
        g_t13_4.obj = nullptr;
        return false;
    }

    g_t13_4.counters_map = bpf_object__find_map_by_name(g_t13_4.obj, "pkt_counters");
    g_t13_4.syn_map      = bpf_object__find_map_by_name(g_t13_4.obj, "syn_per_src");
    g_t13_4.alerts_map   = bpf_object__find_map_by_name(g_t13_4.obj, "alerts");
    if (!g_t13_4.counters_map || !g_t13_4.syn_map || !g_t13_4.alerts_map) {
        std::fprintf(stderr, "[T13.4] missing map (counters=%p syn=%p alerts=%p)\n",
                     (void*)g_t13_4.counters_map, (void*)g_t13_4.syn_map,
                     (void*)g_t13_4.alerts_map);
        bpf_object__close(g_t13_4.obj);
        g_t13_4.obj = nullptr;
        return false;
    }

    // Attach XDP in SKB mode (works on any driver, no native driver needed)
    int prog_fd = bpf_program__fd(g_t13_4.prog);
    if (bpf_xdp_attach(ifindex, prog_fd, XDP_FLAGS_SKB_MODE, nullptr) != 0) {
        std::fprintf(stderr, "[T13.4] bpf_xdp_attach(%s) failed: %s\n",
                     ifname.c_str(), std::strerror(errno));
        bpf_object__close(g_t13_4.obj);
        g_t13_4.obj = nullptr;
        return false;
    }

    // Set up ring buffer consumer
    int alerts_fd = bpf_map__fd(g_t13_4.alerts_map);
    g_t13_4.rb = ring_buffer__new(alerts_fd, t13_4_handle_event, nullptr, nullptr);
    if (!g_t13_4.rb) {
        std::fprintf(stderr, "[T13.4] ring_buffer__new failed\n");
        bpf_xdp_detach(ifindex, XDP_FLAGS_SKB_MODE, nullptr);
        bpf_object__close(g_t13_4.obj);
        g_t13_4.obj = nullptr;
        return false;
    }

    g_t13_4.ifindex = ifindex;
    g_t13_4.scan_event_cb = scan_event_cb;
    g_t13_4.running = true;

    std::fprintf(stderr, "[T13.4] XDP attached to %s (ifindex=%d, SKB mode, "
                          "scan threshold=50 SYNs/window)\n",
                 ifname.c_str(), ifindex);
    return true;
}

// Poll ring buffer for events. Returns number of events consumed.
// Should be called periodically from the agent's main event loop.
int t13_4_xdp_poll(int timeout_ms = 100) {
    if (!g_t13_4.running || !g_t13_4.rb) return 0;
    return ring_buffer__poll(g_t13_4.rb, timeout_ms);
}

// Read packet counters (for /metrics endpoint).
// Returns total packets per protocol [TCP, UDP, ICMP, OTHER].
bool t13_4_xdp_get_counters(uint64_t* out_tcp, uint64_t* out_udp,
                            uint64_t* out_icmp, uint64_t* out_other) {
    if (!g_t13_4.running || !g_t13_4.counters_map) return false;
    int fd = bpf_map__fd(g_t13_4.counters_map);

    auto read_one = [fd](uint32_t idx) -> uint64_t {
        uint64_t values[256] = {0};
        if (bpf_map_lookup_elem(fd, &idx, values) != 0) return 0;
        uint64_t total = 0;
        for (int c = 0; c < 256; ++c) total += values[c];
        return total;
    };

    *out_tcp   = read_one(0);
    *out_udp   = read_one(1);
    *out_icmp  = read_one(2);
    *out_other = read_one(3);
    return true;
}

// Stop and detach. Safe to call multiple times.
void t13_4_xdp_stop() {
    std::lock_guard<std::mutex> lk(g_t13_4_mtx);
    if (!g_t13_4.running) return;

    if (g_t13_4.rb) {
        ring_buffer__free(g_t13_4.rb);
        g_t13_4.rb = nullptr;
    }
    if (g_t13_4.ifindex > 0) {
        bpf_xdp_detach(g_t13_4.ifindex, XDP_FLAGS_SKB_MODE, nullptr);
    }
    if (g_t13_4.obj) {
        bpf_object__close(g_t13_4.obj);
        g_t13_4.obj = nullptr;
    }
    g_t13_4.running = false;
    std::fprintf(stderr, "[T13.4] detached from ifindex %d\n", g_t13_4.ifindex);
}

} // namespace ebpf
