#!/usr/bin/env python3
"""
T14.2 — C-03 AppArmor profile dynamique.

Génère un fragment local /etc/apparmor.d/local/usr.bin.logsoc-agent
avec des règles `path r` ciblées pour chaque watch_path + scan_path
extrait de /etc/logsoc-agent/config.json.

Stratégie : additif (le profil principal garde `/** r` en fallback).
Les règles locales s'ajoutent par-dessus et restreignent seulement les
chemins explicitement listés. Si un FIM scan touche un path non-listé,
le `/** r` du profil principal couvre toujours (pas de régression).

KISS : shell + python3 stdlib (pas de dépendance ajoutée). Le postinst
appelle ce script après avoir installé le .deb principal.

Refs:
- AppArmor local includes: https://manpages.ubuntu.com/manpages/latest/man5/apparmor.d.5.html
  ("#include <local/>" dans le profil principal charge /etc/apparmor.d/local/<basename>)
- C-03 finding: rapport Nova 2026-06-16, profile `/** r` trop permissif
- T13.5: AppArmor hardening initial (DENIED baseline 0.03/sec)
"""
import json
import os
import sys
from pathlib import Path

CONFIG_PATH = "/etc/logsoc-agent/config.json"
PROFILE_LOCAL = "/etc/apparmor.d/local/usr.bin.logsoc-agent"
PROFILE_NAME = "usr.bin.logsoc-agent"
APPA_PARSER = "/usr/sbin/apparmor_parser"

def is_directory(path: str) -> bool:
    """Check if path is an existing directory (without resolving symlinks)."""
    try:
        return os.path.isdir(path) and not os.path.islink(path)
    except OSError:
        return False

def path_to_appa(path: str) -> str:
    """Convert a watch_path to an AppArmor rule.

    - If it's a directory: emit 'path/ r,' and 'path/** r,'
    - If it's a file: emit 'path r,'
    - If it doesn't exist yet: emit a wildcard anyway (better safe than sorry
      for FIM, which should be able to watch newly-created files)
    """
    path = path.rstrip("/")
    if not path or not path.startswith("/"):
        return ""  # invalid, skip
    rules = []
    if is_directory(path):
        rules.append(f"  {path}/ r,")
        rules.append(f"  {path}/** r,")
    else:
        # Could be a file (existing) or a path that doesn't exist yet.
        # For FIM, we want to be able to read it once it appears.
        # Use the parent dir to give a broader allow (the parent is
        # usually a directory we know about, e.g. /etc, /var/log).
        rules.append(f"  {path} r,")
        # Also allow the parent dir (needed for fanotify path resolution
        # which stats the parent of the watched file).
        parent = os.path.dirname(path)
        if parent and parent != "/" and is_directory(parent):
            rules.append(f"  {parent}/ r,")
    return "\n".join(rules)

def generate_fragment(config: dict) -> str:
    """Build the AppArmor local fragment content."""
    paths = set()

    # 1) fim.watch_paths (FIM targets)
    fim = config.get("fim", {})
    for p in fim.get("watch_paths", []):
        paths.add(p)

    # 2) scan_paths (AppCollector reads)
    for p in config.get("scan_paths", []):
        paths.add(p)

    # 3) yara ruleset directory (if defined in config, fallback /etc/logsoc-agent/yara/)
    yara_dir = config.get("yara_ruleset_dir", "/etc/logsoc-agent/yara")
    if yara_dir:
        paths.add(yara_dir)

    # 4) data_dir (already in main profile as /var/lib/logsoc-agent/** rwlk,
    #    but include for completeness if user customized it)
    data_dir = config.get("data_dir", "/var/lib/logsoc-agent")
    if data_dir and data_dir != "/var/lib/logsoc-agent":
        paths.add(data_dir)

    # Sort and dedupe
    paths = sorted(paths)

    header = f"""# T14.2 — C-03 AppArmor profile dynamique.
# AUTO-GENERATED by /usr/share/logsoc-agent/generate-apparmor-local.py
# DO NOT EDIT BY HAND. Regenerated on every .deb install (postinst).
#
# Strategy: ADDITIVE — the main profile /etc/apparmor.d/{PROFILE_NAME}
# keeps `/** r` as a fallback. This fragment adds specific `path r`
# rules for the FIM watch_paths and scan_paths declared in
# /etc/logsoc-agent/config.json. AppArmor evaluates the union, so
# these rules don't RESTRICT what `/** r` allows — they make the
# policy EXPLICIT about which paths the agent is *supposed* to read.
#
# Future: T14.2b will REMOVE `/** r` from the main profile and rely
# ONLY on this fragment + path-specific rules in the main profile.
# For now (POC), we ship additively to avoid breaking anything.
#
# Paths declared in config.json: {len(paths)}
"""
    if not paths:
        body = "  # (no fim.watch_paths or scan_paths declared in config.json)\n"
    else:
        body = "\n".join(path_to_appa(p) for p in paths if p)
        body += "\n"

    return header + body

def main() -> int:
    if not os.path.exists(CONFIG_PATH):
        print(f"  [SKIP] config.json not found at {CONFIG_PATH}", file=sys.stderr)
        return 0  # not an error — fresh install before config exists

    try:
        with open(CONFIG_PATH) as f:
            config = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"  [WARN] could not parse {CONFIG_PATH}: {e}", file=sys.stderr)
        return 0

    fragment = generate_fragment(config)

    # Write the fragment
    os.makedirs(os.path.dirname(PROFILE_LOCAL), exist_ok=True)
    with open(PROFILE_LOCAL, "w") as f:
        f.write(fragment)
    print(f"  AppArmor local fragment: {PROFILE_LOCAL} ({len(fragment)} bytes)")

    # Reload AppArmor to pick up the new fragment
    if os.path.exists(APPA_PARSER):
        # -W = warn on errors, -r = replace existing, local include picks up
        # the /etc/apparmor.d/local/<name> fragment automatically
        ret = os.system(f"{APPA_PARSER} -W -r /etc/apparmor.d/{PROFILE_NAME} 2>&1")
        if ret != 0:
            print(f"  [WARN] apparmor_parser returned {ret}", file=sys.stderr)
            return 1
        print(f"  AppArmor reloaded: /etc/apparmor.d/{PROFILE_NAME}")
    else:
        print(f"  [SKIP] apparmor_parser not found, fragment written but not loaded", file=sys.stderr)

    return 0

if __name__ == "__main__":
    sys.exit(main())
