#!/usr/bin/env bash
# scripts/build_ebpf.sh — Compile eBPF C probes → CO-RE objects → embedded header
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EBPF_DIR="${REPO_ROOT}/src/ebpf"
HEADER_FILE="${REPO_ROOT}/src/ebpf_payload.h"
# T13.4: XDP program (in-kernel SYN scan detection) gets its own header
T13_4_HEADER_FILE="${REPO_ROOT}/src/t13_4_xdp_payload.h"
T13_4_BPF_SRC="${EBPF_DIR}/t13_4_xdp.bpf.c"
T13_4_BPF_OBJ="${EBPF_DIR}/t13_4_xdp.bpf.o"

# Kernel libbpf headers shipped with kernel tools
LIBBPF_INCLUDE="/usr/src/linux-headers-$(uname -r)/tools/bpf/resolve_btfids/libbpf/include"

CLANG=$(command -v clang-17 2>/dev/null || command -v clang 2>/dev/null || true)
if [[ -z "${CLANG}" ]]; then
    echo "ERROR: clang introuvable" >&2
    exit 1
fi

CLANG_VER=$(${CLANG} --version | head -1 | grep -oE '[0-9]+' | head -1)
if [[ "${CLANG_VER}" -lt 15 ]]; then
    echo "ERROR: clang ${CLANG_VER} < 15 requis" >&2
    exit 1
fi
echo "[+] clang ${CLANG_VER} détecté"

LLVM_OBJDUMP=$(command -v llvm-objdump-17 2>/dev/null || command -v llvm-objdump-18 2>/dev/null || command -v llvm-objdump-19 2>/dev/null || command -v llvm-objdump 2>/dev/null || true)
if [[ -z "${LLVM_OBJDUMP}" ]]; then
    echo "ERROR: llvm-objdump introuvable" >&2
    exit 1
fi
echo "[+] llvm-objdump: ${LLVM_OBJDUMP}"

# Vérifier vmlinux.h
if [[ ! -f "${EBPF_DIR}/vmlinux.h" ]]; then
    echo "[!] Génération de vmlinux.h..."
    bpftool btf dump file /sys/kernel/btf/vmlinux format c > "${EBPF_DIR}/vmlinux.h"
fi

CFLAGS="-O2 -g -target bpf -D__TARGET_ARCH_x86"
CFLAGS="${CFLAGS} -D__BPF_TRACING__ -DKBUILD_MODNAME=\"logsoc\""
CFLAGS="${CFLAGS} -Wall -Wno-unused-value -Wno-pointer-sign -Wno-compare-distinct-pointer-types"
INCLUDES="-I${EBPF_DIR} -I${LIBBPF_INCLUDE}"

# ============================================================
# Part 1: skel_soc — observability probes (FIM, execve, unlink, etc.)
#         These have been around since V3.x. Do NOT remove.
# ============================================================
for src in skel_soc; do
    SRC="${EBPF_DIR}/${src}.c"
    OUT="${EBPF_DIR}/${src}.o"
    echo "[+] Compilation ${src}.c → ${src}.o"
    ${CLANG} ${CFLAGS} ${INCLUDES} -c "${SRC}" -o "${OUT}"
    # Strip debug symbols to reduce embedded payload size (keep BTF)
    llvm-strip-17 --strip-debug "${OUT}" 2>/dev/null || llvm-strip --strip-debug "${OUT}" 2>/dev/null || true
done

echo "[+] Vérification BTF..."
for src in skel_soc; do
    OUT="${EBPF_DIR}/${src}.o"
    if ! ${LLVM_OBJDUMP} -h "${OUT}" | grep -qi btf; then
        echo "ERROR: BTF manquant dans ${src}.o" >&2
        exit 1
    fi
    echo "    ${src}.o OK (BTF présent)"
done

echo "[+] Génération de ${HEADER_FILE} ..."
{
    echo "/* ebpf_payload.h — Auto-generated by scripts/build_ebpf.sh */"
    echo "#ifndef __EBPF_PAYLOAD_H__"
    echo "#define __EBPF_PAYLOAD_H__"
    echo ""
    for src in skel_soc; do
        OUT="${EBPF_DIR}/${src}.o"
        xxd -i "${OUT}" | sed "s/unsigned char .*\[\] =/unsigned char ${src}_bpf[] =/"
        echo ""
    done
    echo "#endif"
} > "${HEADER_FILE}"

SIZE=$(stat -c%s "${HEADER_FILE}" 2>/dev/null || stat -f%z "${HEADER_FILE}" 2>/dev/null)
echo "[+] ${HEADER_FILE} généré (${SIZE} octets)"

# ============================================================
# Part 2 (T13.4): t13_4_xdp — in-kernel SYN scan detection via XDP.
#   This is a SECONDARY observability program. It runs in parallel
#   with skel_soc (kernel-side attach — no userspace packet copy).
#   It feeds into the same EventBus (T12) via a separate ring buffer.
#
#   We do NOT replace pcap_collector with this — both run side-by-side
#   until T13.4' (the full XDP-driven pipeline).
# ============================================================
if [[ -f "${T13_4_BPF_SRC}" ]]; then
    echo "[T13.4] Compilation t13_4_xdp.bpf.c → t13_4_xdp.bpf.o"
    ${CLANG} ${CFLAGS} ${INCLUDES} -c "${T13_4_BPF_SRC}" -o "${T13_4_BPF_OBJ}"
    # Don't strip — the .o is small (16KB) and stripping may break BTF
    if ! ${LLVM_OBJDUMP} -h "${T13_4_BPF_OBJ}" | grep -qi btf; then
        echo "WARNING: BTF manquant dans t13_4_xdp.bpf.o (sera chargé quand même)" >&2
    fi

    echo "[T13.4] Génération de ${T13_4_HEADER_FILE} ..."
    {
        echo "/* t13_4_xdp_payload.h — Auto-generated by scripts/build_ebpf.sh */"
        echo "/* Source: src/ebpf/t13_4_xdp.bpf.c (XDP SYN scan detector) */"
        echo "/* Loaded by: src/ebpf/loader.cpp via bpf_object__open_mem() */"
        echo "#ifndef __T13_4_XDP_PAYLOAD_H__"
        echo "#define __T13_4_XDP_PAYLOAD_H__"
        echo ""
        echo "#include <cstdint>"
        echo ""
        # Note: sed transforms the absolute-path-prefixed array name
        # (e.g. "_home_hermes_log_soc_ai_repo_agent_src_ebpf_t13_4_xdp_bpf_o[]")
        # into "t13_4_xdp_bpf[]" — the symbol the loader.cpp expects.
        xxd -i "${T13_4_BPF_OBJ}" | sed 's/^unsigned char [^=]*\[\] =/unsigned char t13_4_xdp_bpf[] =/'
        echo ""
        echo "#endif // __T13_4_XDP_PAYLOAD_H__"
    } > "${T13_4_HEADER_FILE}"

    SIZE=$(stat -c%s "${T13_4_HEADER_FILE}" 2>/dev/null || stat -f%z "${T13_4_HEADER_FILE}" 2>/dev/null)
    echo "[T13.4] ${T13_4_HEADER_FILE} généré (${SIZE} octets)"
fi

echo "[+] Terminé."
